---
- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  when: baseline_upgrade_packages

- name: Install QEMU guest agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: baseline_install_qemu_guest_agent

- name: Start and enable QEMU guest agent
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    state: started
    enabled: true
  when: baseline_install_qemu_guest_agent

- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ baseline_debian_packages }}"
    state: present
    update_cache: true

- name: Start and enable ufw
  ansible.builtin.systemd_service:
    name: ufw
    enabled: true
    state: started
  when: baseline_enable_firewall

- name: Allow services
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ baseline_allowed_ports }}"
  when: baseline_enable_firewall

- name: Add non-root user
  ansible.builtin.user:
    name: "{{ baseline_nonroot_user }}"
    groups: sudo
    shell: /bin/bash

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: "{{ baseline_nonroot_user }}"
    key: "{{ baseline_ssh_authorized_keys | join('\n') }}"
    state: present
    exclusive: true

- name: Copy 50-sudo-nopasswd
  ansible.builtin.copy:
    src: ubuntu/50-sudo-nopasswd
    dest: /etc/sudoers.d/50-sudo-nopasswd
    owner: root
    group: root
    mode: '0440'

- name: Copy sshd_config
  ansible.builtin.copy:
    src: ubuntu/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart sshd

- name: Copy 50unattended-upgrades
  ansible.builtin.template:
    src: ubuntu/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  notify: Restart unattended-upgrades
