---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Include RHEL tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_facts["os_family"] == "RedHat"

- name: Include OpenBSD tasks
  ansible.builtin.include_tasks: openbsd.yml
  when: ansible_facts["os_family"] == "OpenBSD"

- name: Include Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["os_family"] == "Debian"
