---
- name: Upgrade packages
  community.general.openbsd_pkg:
    name: '*'
    state: latest
  when: baseline_upgrade_packages

- name: Install baseline packages
  community.general.openbsd_pkg:
    name: "{{ baseline_openbsd_packages }}"
    state: present

- name: Copy pf.conf
  ansible.builtin.template:
    src: openbsd/pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: '0600'
  notify: Reload pf.conf
  when: baseline_enable_firewall

- name: Add non-root user
  ansible.builtin.user:
    name: "{{ baseline_nonroot_user }}"
    groups: wheel
    shell: /bin/ksh

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: "{{ baseline_nonroot_user }}"
    key: "{{ baseline_ssh_authorized_keys | join('\n') }}"
    state: present
    exclusive: true

- name: Copy doas.conf
  ansible.builtin.template:
    src: openbsd/doas.conf.j2
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: '0644'

- name: Copy sshd_config
  ansible.builtin.copy:
    src: openbsd/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: '0644'
  notify: Restart sshd

- name: Schedule pkg_add -u
  ansible.builtin.cron:
    name: pkg_add -u
    minute: 0
    hour: 2
    job: /usr/sbin/pkg_add -u

- name: Schedule syspatch
  ansible.builtin.cron:
    name: syspatch
    minute: 0
    hour: 4
    job: /usr/sbin/syspatch
