---
- name: Register RHEL subscription
  community.general.redhat_subscription:
    activationkey: "{{ baseline_redhat_activation_key }}"
    org_id: "{{ baseline_redhat_org_id }}"
    syspurpose:
      usage: "{{ baseline_rhel_syspurpose_usage }}"
      role: "{{ baseline_rhel_syspurpose_role }}"
      service_level_agreement: "{{ baseline_rhel_syspurpose_service_level_agreement }}"
      sync: true
  when: baseline_redhat_subscription

- name: Enable repos
  community.general.rhsm_repository:
    name: "{{ baseline_redhat_repos }}"
  when: baseline_redhat_subscription and baseline_redhat_repos

- name: Upgrade packages
  ansible.builtin.dnf:
    upgrade: yes
    update_cache: yes
  when: baseline_upgrade_packages

- name: Install QEMU guest agent
  ansible.builtin.dnf:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: baseline_install_qemu_guest_agent

- name: Start and enable QEMU guest agent
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    state: started
    enabled: true
  when: baseline_install_qemu_guest_agent

- name: Install baseline packages
  ansible.builtin.dnf:
    name: "{{ baseline_rhel_packages }}"
    state: present
    update_cache: true

- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present
    update_cache: true
  when: baseline_enable_firewall

- name: Start and enable firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: true
    state: started
  when: baseline_enable_firewall

- name: Allow services
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ baseline_allowed_ports }}"
  when: baseline_enable_firewall

- name: Add non-root user
  ansible.builtin.user:
    name: "{{ baseline_nonroot_user }}"
    groups: wheel
    shell: /bin/bash

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: "{{ baseline_nonroot_user }}"
    key: "{{ baseline_ssh_authorized_keys | join('\n') }}"
    state: present
    exclusive: true

- name: Copy 50-wheel-nopasswd
  ansible.builtin.copy:
    src: rhel/50-wheel-nopasswd
    dest: /etc/sudoers.d/50-wheel-nopasswd
    owner: root
    group: root
    mode: 0440

- name: Copy sshd_config
  ansible.builtin.copy:
    src: rhel/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Restart sshd

- name: Copy automatic.conf
  ansible.builtin.template:
    src: rhel/automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644
