---
hostname: "{{ inventory_hostname }}"
upgrade_packages: false
install_qemu_guest_agent: false
timezone: UTC
enable_firewall: true
allowed_ports:
  - port: 22
    proto: tcp
redhat_subscription: false
redhat_repos: []
rhel_syspurpose_usage: Development/Test
rhel_syspurpose_role: RHEL Server
rhel_syspurpose_service_level_agreement: Self-Support
debian_baseline_packages:
  - unattended-upgrades
  - tmux
  - vim
  - net-tools
rhel_baseline_packages:
  - dnf-automatic
  - tmux
  - vim
  - net-tools
openbsd_baseline_packages: []
