---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Netstart  # noqa no-changed-when
  ansible.builtin.command:
    cmd: /bin/sh /etc/netstart

- name: Reload pf.conf and flush rules  # noqa no-changed-when
  ansible.builtin.command:
    cmd: pfctl -F rules -f /etc/pf.conf

- name: Restart dhcpd
  ansible.builtin.service:
    name: dhcpd
    state: restarted

- name: Reset external network interface  # noqa no-changed-when
  ansible.builtin.command:
    cmd: sh /etc/netstart {{ pf_egress_if }}

- name: Restart nsd
  ansible.builtin.service:
    name: nsd
    state: restarted

- name: Restart unbound
  ansible.builtin.service:
    name: unbound
    state: restarted
