---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    state: restarted

- name: Reload pf.conf
  ansible.builtin.shell:
    cmd: pfctl -e -f /etc/pf.conf
