---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    state: restarted

- name: Reload pf.conf  # noqa no-changed-when
  ansible.builtin.command:
    cmd: pfctl -f /etc/pf.conf
