---
dependencies: []
galaxy_info:
  role_name: baseline
  description: Apply baseline settings to a server
  author: Brian Reumere <brian@mutualaid.info>
  license: ISC
  min_ansible_version: '2.15'
  platforms:
    - name: EL
      versions:
        - 9
    - name: Ubuntu
      versions:
        - jammy
    - name: OpenBSD
      versions:
        - 7.2
        - 7.3
        - 7.4
